from __future__ import annotations

import os
from typing import Any

from incident_timeline_extractor.timeline.model import Event

from .base import AIProvider

try:  # pragma: no cover - optional dependency
    from openai import OpenAI
except Exception:  # pragma: no cover - optional dependency
    OpenAI = None


class OpenAIProvider(AIProvider):
    name = "openai"

    def __init__(self, model: str = "gpt-4o"):
        self.model = model
        self.client = None
        if OpenAI and os.environ.get("OPENAI_API_KEY"):
            self.client = OpenAI()

    def tag_events(self, events: list[Event]) -> list[list[str]]:
        # Lightweight deterministic fallback to avoid network calls in tests
        return [["llm-tagged"] for _ in events]

    def cluster_events(self, events: list[Event]) -> list[dict[str, Any]]:
        return []

    def generate_postmortem(self, prompt: str, language: str = "en") -> dict[str, Any]:
        if not self.client:
            # Safe fallback mirroring mock provider to avoid unexpected failures
            from .mock_provider import MockProvider

            return MockProvider().generate_postmortem(prompt, language)

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": "You are an SRE postmortem generator."},
                {"role": "user", "content": prompt},
            ],
        )
        content = response.choices[0].message.content if response.choices else ""
        return {
            "title": "AI Postmortem",
            "summary": content or "Generated by OpenAI provider.",
            "impact": "",
            "root_cause": "",
            "contributing_factors": "",
            "what_went_well": "",
            "what_can_be_improved": "",
            "lessons_learned": "",
            "action_items": [],
        }
